sudo: required

services:
  - docker

branches:
  only:
  - master

script:
  - echo ' ----------------- BUILD  DOCKER IMAGE ----------------- '
  - echo REGISTRY_USER = $REGISTRY_USER && echo REGISTRY_PASS = $REGISTRY_PASS
  - echo 'docker bulid...' && docker build . -t sg_taxi_env_instance
  - echo 'pytest...' && docker run -it sg_taxi_env_instance -c "python -m pytest"
  - echo 'docker test...' docker run -it sg_taxi_env_instance echo 'docker test 123'
  - container_id="` docker ps -a | awk 'FNR == 2 {print $1}'`" && echo container_id = $container_id && image_id="` docker ps -a | awk 'FNR == 2 {print $2}'`" && echo image_id = $image_id 
  - docker ps -a 
  - docker images

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin && echo "docker login OK" || echo "docker login failed"

deploy:
  provider: script
  # docker commit and push 
  script: (echo '--- DEPLOY PART 1 ---' && docker commit $container_id yennanliu/sg_taxi_env_instance:V1 && docker push yennanliu/sg_taxi_env_instance:V1) 

after_deploy: