sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - echo ' ----------------- STEP 1) BUILD DOCKER IMAGE ----------------- '
  - echo REGISTRY_USER = $REGISTRY_USER && echo REGISTRY_PASS = $REGISTRY_PASS
  - echo 'docker bulid...' && docker build . -t sg_taxi_env_instance
  - echo 'docker test...' && docker run -it sg_taxi_env_instance echo 'docker test 123'
  - container_id="` docker ps -a | awk 'FNR == 2 {print $1}'`" && echo container_id = $container_id && image_id="` docker ps -a | awk 'FNR == 2 {print $2}'`" && echo image_id = $image_id 
  - docker ps -a 
  - docker images

script:
  - echo ' -----------------  STEP 2) TEST  ----------------- '
  #- echo 'UNIT TEST' && docker run -it sg_taxi_env_instance /bin/bash -c "pytest -v tests/"  

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin && echo "docker login OK" || echo "docker login failed"
  - (echo '----------------- STEP 3) DOCKER PUSH -----------------' && docker commit $container_id yennanliu/sg_taxi_env_instance:V1 && docker push yennanliu/sg_taxi_env_instance:V1) 

deploy:
  provider: heroku
  api_key:
    secure: "SieoKJzL7xSPjmk6025rcogs3rE30zj6LPj7xfWdl9Rz1tvN24vDjwzpqRC2ofsTk6s773X7xzQx3l69Uf/at5qX0cVfsyE4UjNPy1Ht3Pa8yJTdQIE3dknpXJUfqV1OeMVnRnMk7vuE4k3llB8aYOLQ+Yxs6rzO++oskBBBlZvsIr/sDF9A13Hy+jliT6jgd8InN4PcX47WdUEs6WY0YEsjRy6RZ+Y0qZJ0uZcno1RXz63gJ5Ta5jsgYuY/dXhz+QKHckzfzZJEn/tEFYGBh9nKkyOKodW0C0XlrA+B72CO9dREK+gNnSX29r7VdVoVblqF/J3REFO0DOFSdzT9eLCXW1hMGPLY/86de5GEL49sIobirxOupXpORgSSV2OfpviaXoe5VUljzJphSh8OvTRTydVB/t+0btN8aicxaJk7MsDxNRIVVwaSijNxgF+KrnQTDItWriISM6pTt4e6/W04N72D7K97m1FFa3PuAPV8cnSJmotwskxJ33jlPe3inh1XDcLlpzH4EMZjMLW/J4Uxm72Fy9aoZ34oYRdwyrno9h5ZpfurGxtUi9MkSe3KQ39xtL4VUFX9PDRa/UzHdVFV9bW3U7cfbqIa5yufEK00VZxXOSeujcZ9mXyKh0nu6BdMOrPoa4Oz6RyGXl13km4MJ2qu/+mEYa+1SKsknu8="
  run: "echo '----------------- STEP 4) HEROKU DEPLOY -----------------'"
  app: sgtaxi-heroku-app
  on:
    repo: yennanliu/SGTaxiMap
