sudo: required

services:
  - docker

branches:
  only:
  - master

script:
  - echo ' ----------------- STEP 1) BUILD DOCKER IMAGE ----------------- '
  - echo REGISTRY_USER = $REGISTRY_USER && echo REGISTRY_PASS = $REGISTRY_PASS
  - echo 'docker bulid...' && docker build . -t sg_taxi_env_instance
  - echo 'docker test...' && docker run -it sg_taxi_env_instance echo 'docker test 123'
  - container_id="` docker ps -a | awk 'FNR == 2 {print $1}'`" && echo container_id = $container_id && image_id="` docker ps -a | awk 'FNR == 2 {print $2}'`" && echo image_id = $image_id 
  - docker ps -a 
  - docker images

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin && echo "docker login OK" || echo "docker login failed"
  - (echo '----------------- STEP 2) PUSH TO DOCKER -----------------' && docker commit $container_id yennanliu/sg_taxi_env_instance:V1 && docker push yennanliu/sg_taxi_env_instance:V1) 

deploy:
  provider: heroku
  api_key:
    secure: "nT/x5M0Ki5Za3/GCtdsHh8ZHFZwVGi+C6mcMrpIsnbwCdat65ZU0o+kkVMq5rY/eC6kuB7dHib/Avyv347GFFSRzd/c0r+Hx3xVFam/Weov79dZLhxUarw/khBfTEHZlJO9noq7vxslreMgVXlJcJNwgQSVD5naPoqPxMwecUn0DJUlCPvqhWxcmqhHE5RLpsb18pr7wCovtMj+RGJ4uNJNF7pinUF2aFM0wpDn7accEj3waMHFiL4WFhXbGCPccPXhoJ9Teo06Pjubt715F+YTAYM+3bkebQxmBZTSaH77M90oy85u/nMCHbFpw/hagodaEHO38VmWLLP9qz9wpfDoF6Fha6W7PZX8Mq42HfvCe+semOPK8wAnfLpLkJugUffW0WPOe+PS/zZ3PrenodJJjNJz+it0yitb/ffO/fvMNQq9aaVojEYxXI9S5noX4LrplUS8COznJazW2RO7Xr1vCU2B6uH5PQiFg5/L7xGbyFLSxIGq4V+sy8o1xVEkfvATsiGwrv1YC+WPjo3xjC6DYmQuyVO8eHkK4J41l7kcWrC1AzLPQe4hxap1QlFxDhg73lwh+YWVG6dn4K5ZEyFvPOUjLDCPmrk4iKHgtXQzFxdTmVB17NZiulKXY0nje5Z+3CHw4D7mbT9Nqmen/TlKJsCPdai2DJJ+QBoaeI40="
  run: - "echo '----------------- STEP 3) DEPLOY TO HEROKU -----------------'"
  app: sgtaxi-heroku-app
  on:
    repo: yennanliu/SGTaxiMap

after_deploy: